CREATE TABLE `consent_agreements` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `uid` int(13) NOT NULL DEFAULT '0',
  `approval` enum('Waiting','Approved','Unapproved') NOT NULL DEFAULT 'Waiting',
  `batch-id` int(20) NOT NULL DEFAULT '0',
  `gardian-id` int(20) NOT NULL DEFAULT '0',
  `clientel-id` int(20) NOT NULL DEFAULT '0',
  `hashkey` varchar(12) NOT NULL DEFAULT '',
  `referee` varchar(18) NOT NULL DEFAULT '',
  `callback-url` varchar(255) NOT NULL DEFAULT '',
  `svn-path` varchar(255) NOT NULL DEFAULT '',
  `gardian-filename-pdf` varchar(128) NOT NULL DEFAULT '',
  `clientel-filename-pdf` varchar(128) NOT NULL DEFAULT '',
  `gardian-response-file` varchar(128) NOT NULL DEFAULT '',
  `clientel-response-file` varchar(128) NOT NULL DEFAULT '',
  `response-waiting` enum('Gardian','Clientel','Both') NOT NULL DEFAULT 'Both',
  `response-sourced` enum('Gardian','Clientel','Both') NOT NULL DEFAULT 'Both',
  `response-comment` mediumtext,
  `response-network` mediumtext,
  `response-notified` int(11) NOT NULL DEFAULT '0',
  `response-weight` int(11) NOT NULL DEFAULT '0',
  `response-gardian-weight` int(11) NOT NULL DEFAULT '0',
  `response-clientel-weight` int(11) NOT NULL DEFAULT '0',
  `email-ids` mediumtext,
  `email-agreement-type` enum('None','Gardian','Clientel','Both') NOT NULL DEFAULT 'Both',
  `email-recovery-type` enum('None','Gardian','Clientel','Batch') NOT NULL DEFAULT 'None',
  `email-recovery-guardian-sent` int(11) NOT NULL DEFAULT '0',
  `email-recovery-clientel-sent` int(11) NOT NULL DEFAULT '0',
  `email-from` varchar(64) NOT NULL DEFAULT '',
  `email-sent` int(11) NOT NULL DEFAULT '0',
  `email-views` int(11) NOT NULL DEFAULT '0',
  `email-viewed` int(11) NOT NULL DEFAULT '0',
  `email-gardian-sent` int(11) NOT NULL DEFAULT '0',
  `email-gardian-views` int(11) NOT NULL DEFAULT '0',
  `email-gardian-viewed` int(11) NOT NULL DEFAULT '0',
  `email-clientel-sent` int(11) NOT NULL DEFAULT '0',
  `email-clientel-views` int(11) NOT NULL DEFAULT '0',
  `email-clientel-viewed` int(11) NOT NULL DEFAULT '0',
  `email-remiders-sent` int(11) NOT NULL DEFAULT '0',
  `email-remiders-views` int(11) NOT NULL DEFAULT '0',
  `email-remiders-viewed` int(11) NOT NULL DEFAULT '0',
  `email-progress-sent` int(11) NOT NULL DEFAULT '0',
  `email-progress-views` int(11) NOT NULL DEFAULT '0',
  `email-progress-viewed` int(11) NOT NULL DEFAULT '0',
  `email-recovery-sent` int(11) NOT NULL DEFAULT '0',
  `email-recovery-views` int(11) NOT NULL DEFAULT '0',
  `email-recovery-viewed` int(11) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `emailed` int(11) NOT NULL DEFAULT '0',
  `response` int(11) NOT NULL DEFAULT '0',
  `recovery` int(11) NOT NULL DEFAULT '0',
  `reminde` int(11) NOT NULL DEFAULT '0',
  `timeout` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`approval`,`batch-id`,`gardian-id`,`clientel-id`,`hashkey`,`email-agreement-type`,`created`,`emailed`,`response`,`reminde`,`timeout`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_batches` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` int(13) NOT NULL DEFAULT '0',
  `hashkey` varchar(12) NOT NULL DEFAULT '',
  `referee` varchar(18) NOT NULL DEFAULT '',
  `org` varchar(64) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `email` varchar(196) NOT NULL DEFAULT '',
  `phone` varchar(20) NOT NULL DEFAULT '',
  `message` mediumtext,
  `event` mediumtext,
  `cc` mediumtext,
  `bcc` mediumtext,
  `callback-url` varchar(255) NOT NULL DEFAULT '',
  `email-agreement-type` enum('Gardian','Clientel','Both') NOT NULL DEFAULT 'Both',
  `csv-lines` int(11) NOT NULL DEFAULT '0',
  `csv-bytes` int(11) NOT NULL DEFAULT '0',
  `csv-md5` varchar(32) NOT NULL DEFAULT ',',
  `csv-field` varchar(8) NOT NULL DEFAULT ',',
  `csv-terminated` varchar(8) NOT NULL DEFAULT '\n',
  `csv-string` varchar(8) NOT NULL DEFAULT '"',
  `response-weight` int(11) NOT NULL DEFAULT '0',
  `response-gardian-weight` int(11) NOT NULL DEFAULT '0',
  `response-clientel-weight` int(11) NOT NULL DEFAULT '0',
  `email-from` varchar(64) NOT NULL DEFAULT '',
  `email-sent` int(11) NOT NULL DEFAULT '0',
  `email-views` int(11) NOT NULL DEFAULT '0',
  `email-viewed` int(11) NOT NULL DEFAULT '0',
  `email-gardian-sent` int(11) NOT NULL DEFAULT '0',
  `email-gardian-views` int(11) NOT NULL DEFAULT '0',
  `email-gardian-viewed` int(11) NOT NULL DEFAULT '0',
  `email-clientel-sent` int(11) NOT NULL DEFAULT '0',
  `email-clientel-views` int(11) NOT NULL DEFAULT '0',
  `email-clientel-viewed` int(11) NOT NULL DEFAULT '0',
  `email-remiders-sent` int(11) NOT NULL DEFAULT '0',
  `email-remiders-views` int(11) NOT NULL DEFAULT '0',
  `email-remiders-viewed` int(11) NOT NULL DEFAULT '0',
  `email-progress-sent` int(11) NOT NULL DEFAULT '0',
  `email-progress-views` int(11) NOT NULL DEFAULT '0',
  `email-progress-viewed` int(11) NOT NULL DEFAULT '0',
  `email-recovery-sent` int(11) NOT NULL DEFAULT '0',
  `email-recovery-views` int(11) NOT NULL DEFAULT '0',
  `email-recovery-viewed` int(11) NOT NULL DEFAULT '0',
  `agreements` int(11) NOT NULL DEFAULT '0',
  `gardians-created` int(11) NOT NULL DEFAULT '0',
  `clientel-created` int(11) NOT NULL DEFAULT '0',
  `gardians-existed` int(11) NOT NULL DEFAULT '0',
  `clientel-existed` int(11) NOT NULL DEFAULT '0',
  `agreements-failed` int(11) NOT NULL DEFAULT '0',
  `gardians-failed` int(11) NOT NULL DEFAULT '0',
  `clientel-failed` int(11) NOT NULL DEFAULT '0',
  `agreements-approved` int(11) NOT NULL DEFAULT '0',
  `gardians-approved` int(11) NOT NULL DEFAULT '0',
  `clientel-approved` int(11) NOT NULL DEFAULT '0',
  `agreements-unapproved` int(11) NOT NULL DEFAULT '0',
  `gardians-unapproved` int(11) NOT NULL DEFAULT '0',
  `clientel-unapproved` int(11) NOT NULL DEFAULT '0',
  `agreements-recovery` int(11) NOT NULL DEFAULT '0',
  `gardians-recovery` int(11) NOT NULL DEFAULT '0',
  `clientel-recovery` int(11) NOT NULL DEFAULT '0',
  `agreements-recovered` int(11) NOT NULL DEFAULT '0',
  `gardians-recovered` int(11) NOT NULL DEFAULT '0',
  `clientel-recovered` int(11) NOT NULL DEFAULT '0',
  `approvals` int(11) NOT NULL DEFAULT '0',
  `reminders` int(11) NOT NULL DEFAULT '0',
  `recovery` int(11) NOT NULL DEFAULT '0',
  `created` int(11) NOT NULL DEFAULT '0',
  `timeout` int(11) NOT NULL DEFAULT '0',
  `reported` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`hashkey`,`email`,`timeout`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_callbacks` (
  `when` int(12) NOT NULL,
  `uri` varchar(250) NOT NULL DEFAULT '',
  `timeout` int(4) NOT NULL DEFAULT '0',
  `connection` int(4) NOT NULL DEFAULT '0',
  `data` mediumtext NOT NULL,
  `queries` mediumtext NOT NULL,
  `fails` int(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`when`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_clientel` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` int(13) NOT NULL DEFAULT '0',
  `hashkey` varchar(12) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `email` varchar(196) NOT NULL DEFAULT '',
  `phone` varchar(20) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT '0',
  `emailed` int(11) NOT NULL DEFAULT '0',
  `response` int(11) NOT NULL DEFAULT '0',
  `undelivered` int(11) NOT NULL DEFAULT '0',
  `recovered` int(11) NOT NULL DEFAULT '0',
  `recovery-id` int(20) NOT NULL DEFAULT '0',
  `agreement-ids` mediumtext,
  `email-views` int(11) NOT NULL DEFAULT '0',
  `email-viewed` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`hashkey`,`name`,`email`,`phone`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_emails` (
  `id` int(32) NOT NULL AUTO_INCREMENT,
  `approval` enum('Delivered','Undelivered','Unknown') NOT NULL DEFAULT 'Unknown',
  `email-type` enum('Agreement','Reminder','Recovery','Progress','Unknown') NOT NULL DEFAULT 'Unknown',
  `email-target` enum('Batch','Gardian','Clientel','Webmaster','Unknown') NOT NULL DEFAULT 'Unknown',
  `agreement-id` int(20) NOT NULL DEFAULT '0',
  `batch-id` int(20) NOT NULL DEFAULT '0',
  `gardian-id` int(20) NOT NULL DEFAULT '0',
  `clientel-id` int(20) NOT NULL DEFAULT '0',
  `email` varchar(196) NOT NULL DEFAULT '',
  `referee` varchar(18) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT '0',
  `timeout` int(11) NOT NULL DEFAULT '0',
  `checked` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`approval`,`email-type`,`email-target`,`email`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_guardians` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `uid` int(13) NOT NULL DEFAULT '0',
  `hashkey` varchar(12) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '',
  `email` varchar(196) NOT NULL DEFAULT '',
  `phone` varchar(20) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT '0',
  `emailed` int(11) NOT NULL DEFAULT '0',
  `response` int(11) NOT NULL DEFAULT '0',
  `undelivered` int(11) NOT NULL DEFAULT '0',
  `recovered` int(11) NOT NULL DEFAULT '0',
  `recovery-id` int(20) NOT NULL DEFAULT '0',
  `agreement-ids` mediumtext,
  `email-views` int(11) NOT NULL DEFAULT '0',
  `email-viewed` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`hashkey`,`name`,`email`,`phone`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `consent_statistics` (
  `id` mediumint(32) NOT NULL AUTO_INCREMENT,
  `key` varchar(64) NOT NULL DEFAULT '',
  `when` int(13) NOT NULL DEFAULT '0',
  `year` int(4) NOT NULL DEFAULT '0',
  `month` int(2) NOT NULL DEFAULT '0',
  `day` int(2) NOT NULL DEFAULT '0',
  `week` int(2) NOT NULL DEFAULT '0',
  `hour` int(2) NOT NULL DEFAULT '0',
  `minute` int(2) NOT NULL DEFAULT '0',
  `seconds` int(2) NOT NULL DEFAULT '0',
  `quarter` enum('0-15','15-30','30-45','45-60') NOT NULL DEFAULT '0-15',
  `day-name` enum('Sun','Sat','Mon','Tue','Wed','Thu','Fri') NOT NULL DEFAULT 'Sun',
  `stat` float(22,9) NOT NULL DEFAULT '0.000000000',
  `adverage` float(22,9) NOT NULL DEFAULT '0.000000000',
  `stdev` float(22,9) NOT NULL DEFAULT '0.000000000',
  PRIMARY KEY (`id`),
  KEY `SEARCH` (`key`,`year`,`month`,`day`,`week`,`hour`,`minute`,`quarter`,`day-name`) USING BTREE KEY_BLOCK_SIZE=32
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
